### ISSUE TITLE
Confusing repo name 

### ISSUE THREAD

**Issue by stacksmith** [hughbarney/femto#3]
See https://github.com/FemtoEmacs/Femto-Emacs
In case you haven't seen it... It comes up in searches and seems to have a following.
EDIT: I think you mention it in README, although I was confused a bit.

**Comment by hughbarney** [comment]
Thanks,  as the main author of that codebase I am aware of the other repository.  Let me know what needs to be explained a bit more and I will update the README.

**Comment by stacksmith** [comment]
It's just me.  Maybe consider disambiguating right at the top - something like "This is femto <blah blah>.  If you are looking for Femto-Emacs click here" or something.  Just a thought, no big deal.

**Comment by hughbarney** [comment]
I wrote most of the Editor code for both versions of Femto and Femto Emacs.

The guys in Brazil first implemented a lisp interpreter based into my Atto Editor codebase.  They tried a few Lisp codebases and settled on FemtoLisp.  

I had specific minimal goals for Atto and did not want it to become a bloated project so I asked the Brazil guys to start a FemtoEmacs repository which I contributed to.  However they mad many changes that often broke other things and would not write to a coding standard so in the end I created my own Femto repository and started from scratch to add a minimal lisp interpreter.

Which whilst FemtoLisp it is a good implementation of Lisp it is 12K likes of code and quite hard to understand.  There was not a lot of documentation and the build system with the Atto codebase was clunky.  After unpicking several bugs and having features broken I decided to create my own master repo so that Femto could be the vision that I wanted it to be.   However I have not spent much time on it and so there are a few features I have not re-implemented yet.  The main one being different syntax highlighting for different languages.  If you try some of the test files in 

If you load  https://github.com/hughbarney/femto/blob/master/docs/hltest.c into FemtoEmacs and scroll line by line you will soonfind the bugs with the syntax highlighting in FemtoEmacs, whereas Femto correctly handles in accurately and provides a design that could be built on.  Rather than the shifting sands of the FemtoEmacs syntax highlighting code that is unsupportable in my view.

**Comment by stacksmith** [comment]
I am more confused than when I started.  By FemtoLisp, do you mean Jeff Bezanson's FemtoLisp?

**Comment by hughbarney** [comment]
> By FemtoLisp, do you mean Jeff Bezanson's FemtoLisp?

Yes.  Mentioned in the Histroy section of the README file.
The history of the repositories is.

atto-----fork -------> FemtoEmacs (with FemtoLisp compiled in)
 |
 |
femto
 |
 2016 onwards
 |
 with TinyLisp compiled in

Hopefully that makes sense.  If you have other questions ask away.

If you could review the History section again and let me know what I would need to do to make it easier to understand I would be grateful. 

I am not actively working on femto ATM and FemtoEmacs has not been touched for 6  years.
Once I withdrew the guys stopped working on it.

What I should have done is forked Atto and asked the Brazil guys to make pull requests into femto - then I would have been able to control the qulaity of the code that went in.  At the time I did not want to do that as I was not sure how much time I would have.  The result though a bit choatic  at least eventually motivated me to write the undo code and to come up with a better design for the syntax highlighting code.

I will pick up femto at some point again, but when I have more time on my hands.

**Comment by hughbarney** [comment]
FemtoEmacs is referenced in the References.  
I am not going to further advertise a version of Femto that I consider to be buggy.
Femto is now the master repository and all future enhancements will be done here.
